global: provide memrchr implementation for macOS
macOS doesn't come with a memrchr() of its own, so let's provide an
implementation it can use. This addresses a build error on macOS.

    CC ../ui-shared.o
../ui-shared.c:1258:50: error: call to undeclared function
      'memrchr'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
 1258 | for (last_slash = path + strlen(path);
      |         (slash = memrchr(path, '/', last_s...
      |                  ^
../ui-shared.c:1258:50: note: did you mean 'memchr'?

memrchr.c was taken from musl-libc and tweaked slightly to build as part
of cgit.

https://git.musl-libc.org/cgit/musl/tree/src/string/memrchr.c

It was modified in the following ways:

- Removed weak_alias() and renamed the function to memrchr().
- Replaced string.h with sys/types.h as the include file being used to
  define size_t.
- Added MIT copyright header. (Musl doesn't include copyright notices
  within individual files.)

Signed-off-by: Markus Mayer <code@mmayer.net>